name: Docker Builder CI

on:
  push:
    branches: master

# https://github.com/docker/build-push-action
jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image
        run: |
          cd $GITHUB_WORKSPACE
          docker build -t nanosaur/nanosaur:latest .
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
