name: nanosaur_robot rebuild

# Reference:
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: [push]

# https://github.com/docker/build-push-action
jobs:

  notify:
    name: "Notify"
    runs-on: ubuntu-latest #self-hosted
    steps:
    - name: Notify
      run: |
        curl -XPOST -u "${{ secrets.API_TOKEN_USERNAME}}:${{secrets.API_TOKEN_GITHUB}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rnanosaur/nanosaur/actions/workflows/docker-image.yml/dispatches --data '{"ref": "master"}'